### ISSUE TITLE
Null hashmap

### ISSUE THREAD

**Issue by Therealnaxos** [Bankmongot/Pfi3_Projektarbete_Grupp2_Desktop#1]
När vi hämtar hashmap innehållandes en String och int, får vi ut null. Där finns värden, syns på Firebase.

if (dataSnapshot.getKey().equals("four")){
Map newPost = (Map) arg0.getValue();
System.out.println("Answer: " + newPost.get("alternative"));
System.out.println("Votes: " + newPost.get("votes"));
}

Detta returnerar, "null", "null".

https://github.com/Bankmongot/Pfi3_Projektarbete_Grupp2_Desktop/blob/master/ScreenSwing/src/se/mah/k3/FireBase.java#L62

**Comment by Therealnaxos** [comment]
![Pic](http://i.imgur.com/5V4M7Un.png)

**Comment by Therealnaxos** [comment]
@k3larra

**Comment by k3larra** [comment]
Är detta aktuellt? O hur reproducerar jag det?
On 20 May 2015 11:54 am, Nils Lindgren notifications@github.com wrote:@k3larra

**Comment by Therealnaxos** [comment]
Ja det är aktuellt. Men det är svårt för dig o reprod. eftersom det kräver både Firebase databasen o android appen igång.

Men vi vet inte hur vi får ut datan ur HashMap. Innehållet ser ut så här:
newPost {four={alternative=Monday, votes=0}, Vote1=1, one={alternative=Saturday, votes=0}, Theme=Circles, Vote3=1, Question=Favorite day?, three={alternative=Wensday, votes=0}, two={alternative=Friday, votes=0}}

Men vi vill ju kunna få ut det i bitar, med sina "underliggande" värden.

**Comment by k3larra** [comment]
@Therealnaxos 
Kolla om det var detta du mendade rad 76 och framåt i Firebase.java?

(Döp om den klassen till något som till exempel GetFireBaseData mycket förvirrande namn, även era klasser Drawpanel och DummyPanel är märkliga namn.

Mvh

/L

**Comment by Therealnaxos** [comment]
@k3larra Ja det var mellan 72 och 85.

Ja dummy & drawpanel är endast provisoriska, ska rätta till namnen.
