### ISSUE TITLE
"No current survey" picture not centered on screen

### ISSUE THREAD

**Issue by Therealnaxos** [Bankmongot/Pfi3_Projektarbete_Grupp2_Desktop#3]
"No current survey" picture not centered on screen

We need to make it adapt to the resolution of the screen.

**Comment by semcni** [comment]
Fixed.
It does not scale but works well with 1024 x 768. Smaller than that isn't needed.

**Comment by Therealnaxos** [comment]
![asd](http://i.imgur.com/Din8YKp.gif)
@Mcni91
